channels:
- conda-forge
dependencies:
- python=3.8
- bokeh
- coverage
- cython
- future
- h5py
- holoviews
- ipykernel
- ipython
- ipyparallel
- jupyter
- matplotlib
- mypy
- nose
- numpy
- numpydoc
- opencv
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- scikit-image
- scikit-learn
- scipy
- tensorflow
- tifffile
- tk
- tqdm
- yapf
